# GET  http://localhost:8080/pokemon/get/ditto
# put  http://localhost:8080/pokemon/catch/121
# Content-Type: application/json
# username: kiki 
# POST  http://localhost:8080/info 
# username: shachar2
# Content-Type: application/json

# {
#   username: 'wqdd'   
# }
POST  http://localhost:8080/info
Content-Type: application/json

{
    "username" : "ory"
}



